version: "3.8"

services:
  recursor:
    image: bobsomers/powerdns-recursor:v1
    ports:
      - "12345:53/udp"

  #authoritative:
    # TODO

  #admin:
    # TODO

  cloudflare:
    image: bobsomers/cloudflare-doh:v1
